// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAvtNetworkEquipment = "avt_network_equipment"

// AvtNetworkEquipment mapped from table <avt_network_equipment>
type AvtNetworkEquipment struct {
	ID         int64      `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	Campus     *string    `gorm:"column:campus;type:varchar(50);comment:校区" json:"campus"`        // 校区
	Building   *string    `gorm:"column:building;type:varchar(50);comment:大楼" json:"building"`    // 大楼
	Floor      *string    `gorm:"column:floor;type:varchar(20);comment:楼层" json:"floor"`          // 楼层
	Room       *string    `gorm:"column:room;type:varchar(50);comment:教室" json:"room"`            // 教室
	Model      *string    `gorm:"column:model;type:varchar(50);comment:设备型号" json:"model"`        // 设备型号
	Position   *string    `gorm:"column:position;type:varchar(100);comment:安装位置" json:"position"` // 安装位置
	IP         *string    `gorm:"column:ip;type:varchar(20);comment:IP地址" json:"ip"`              // IP地址
	CreateTime *time.Time `gorm:"column:create_time;type:datetime" json:"create_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime" json:"update_time"`
}

// TableName AvtNetworkEquipment's table name
func (*AvtNetworkEquipment) TableName() string {
	return TableNameAvtNetworkEquipment
}
