// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysBackendUser = "sys_backend_user"

// SysBackendUser mapped from table <sys_backend_user>
type SysBackendUser struct {
	ID            int64    `gorm:"column:id;type:int;primaryKey;autoIncrement:true" json:"id,string"`
	RealName      string   `gorm:"column:real_name;type:varchar(255);not null" json:"real_name"`
	UserName      string   `gorm:"column:user_name;type:varchar(255);not null" json:"user_name"`
	UserPwd       string   `gorm:"column:user_pwd;type:varchar(255);not null" json:"user_pwd"`
	IsSuper       int64    `gorm:"column:is_super;type:tinyint(1);not null" json:"is_super"`
	Status        int64    `gorm:"column:status;type:int;not null" json:"status"`
	Mobile        string   `gorm:"column:mobile;type:varchar(16);not null" json:"mobile"`
	Email         string   `gorm:"column:email;type:varchar(256);not null" json:"email"`
	Avatar        string   `gorm:"column:avatar;type:varchar(256);not null" json:"avatar"`
	UserType      *int64   `gorm:"column:user_type;type:int;comment:1-系统管理员；" json:"user_type"` // 1-系统管理员；
	OperatorID    *int64   `gorm:"column:operator_id;type:int" json:"operator_id"`
	ParentID      *int64   `gorm:"column:parent_id;type:int;comment:上级id" json:"parent_id"`                          // 上级id
	ParentRoute   *string  `gorm:"column:parent_route;type:varchar(100);comment:所有上级路径 /2/5/10" json:"parent_route"` // 所有上级路径 /2/5/10
	Percentage    *float64 `gorm:"column:percentage;type:decimal(12,2)" json:"percentage"`
	Quota         *float64 `gorm:"column:quota;type:decimal(12,2)" json:"quota"`
	KdxfLoginName *string  `gorm:"column:kdxf_login_name;type:varchar(60);comment:科大讯飞FIF平台login_name" json:"kdxf_login_name"` // 科大讯飞FIF平台login_name
}

// TableName SysBackendUser's table name
func (*SysBackendUser) TableName() string {
	return TableNameSysBackendUser
}
